# Generated by Django 3.2 on 2022-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220319_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Staff'), (2, 'Customer')], default=1),
        ),
    ]
