# Generated by Django 3.2 on 2022-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0004_auto_20220409_0407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Intern',
        ),
        migrations.AlterModelOptions(
            name='intern',
            options={'verbose_name_plural': 'Interns'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Staff'), (2, 'Intern')], default=1, verbose_name='Role'),
        ),
    ]
