# Generated by Django 3.2 on 2022-04-11 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Task name')),
                ('details', models.CharField(max_length=200, verbose_name='Details')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('interns', models.ManyToManyField(blank=True, related_name='task_obj', to=settings.AUTH_USER_MODEL, verbose_name='Interns')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
        ),
    ]
