# Generated by Django 3.2 on 2022-04-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_auto_20220410_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Task name')),
                ('details', models.CharField(max_length=200, verbose_name='Details')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.intern', verbose_name='Intern')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.supervisor', verbose_name='Supervisor')),
            ],
        ),
    ]
